version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohorts_long:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-01-01 to 2021-03-01 by month" --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort1: output/measures/input_measures_*.csv

  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition_measures --output-dir=output/measures
      needs: [generate_cohorts_long]
      outputs:
        moderately_sensitive:
          measure_csv: output/measures/measure_*.csv

  run_model_long:
      run: r:latest analysis/03-createnattrends_codes.R
      needs: [generate_cohorts_long]
      outputs:
        moderately_sensitive:
          log: logs/log-03-createnattrends.txt
          tb01: output/tables/sc03_tb01_nattrends.csv
          fig01: output/plots/sc03_fig01_nattrends.svg
          fig02: output/plots/sc03_fig02_nattrends.svg
          fig03: output/plots/sc03_fig03_pracnatcoverage.svg
          fig04: output/plots/sc03_fig04_pracbyregcoverage.svg
          fig04b: output/plots/sc03_fig04b_pracbyregcoverage.svg

  run_model_measures:
        run: r:latest analysis/02-createtemporal.R
        needs: [generate_cohorts_long,generate_measures]
        outputs:
          moderately_sensitive:
            log: logs/log-02-createtemporal.txt
            red_measures: output/tables/redacted_*.csv
            #figall: output/plots/plot_each_*_practice.svg
            figquant: output/plots/plot_quantiles_*_practice.svg
            figlogquant: output/plots/plot_logquantiles_*_practice.svg


  ### Weekly tallies
  generate_cohorts_weekly2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures_weekly --index-date-range "2019-04-01 to 2021-03-29 by week" --output-dir=output/measures-week
    outputs:
      highly_sensitive:
        cohort: output/measures-week/input_measures_weekly_*.csv

  generate_measures_weekly2021:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures_weekly --output-dir=output/measures-week
    needs: [generate_cohorts_weekly2021]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures-week/measure_*.csv

  run_model_weekly2021:
    run: r:latest analysis/04-weekly2021.R
    needs: [generate_cohorts_weekly2021,generate_measures_weekly2021]
    outputs:
      moderately_sensitive:
        log: logs/log-04-weekly2021.txt
        tab1: output/tables/sc04-weeklynattrend.csv
        figx: output/plots/sc04_*.svg
